Remove test_catch_undef
Since enabling ERROR_ON_UNDEFINED_SYMBOLS this test is now
failing with the wasm backend with:

```
error: undefined symbol: __ubsan_handle_pointer_overflow
error: undefined symbol: __ubsan_handle_type_mismatch_v1
` ``

Did we ever support -fsanitize=undefined?  This test was
orininally added to test we supported -fcatch-undefined-behavior
but did it actually work?

Since as far as I can tell we don't yet support this I'm
inclined to simply remove this test until we do.